### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mr-kelsey** [CISecurity/ArtifactExpressions#68]
ArtifactExpressions/about/about.rst 

https://workbench.cisecurity.org/communities/148

**Comment by JanCooper** [comment]
Hello @rexploreit 
I have verified this is not link in fact broken. Can you please share what problem you are experiencing with the link?

**Comment by mr-kelsey** [comment]
Hello @JanCooper 

I get a  CIS Security Benchmarks 404 Page Not Found error when attempting to follow the link.

I have tried the link while I am already logged in.  And I have tried the link when I wasn't logged in already.  In the case of the latter, the link takes me to the CIS workbench login form.  After entering my credentials, I am  again met with the 404 page.

**Comment by JanCooper** [comment]
Hi @rexploreit. That community was set up to help SecureSuite members forking or tailoring their benchmarks. Are you a SecureSuite member? If so, I'll need to verify your Workbench login is set up appropriately to view the community.

**Comment by mr-kelsey** [comment]
Hello again, @JanCooper 

I am not a SecureSuite member.  I didn't notice anything in the docs I read referencing needing to be a part of that team.  My apologies.  Thanks so much for looking into it.  Sorry to have wasted your time.

**Comment by JanCooper** [comment]
@rexploreit
For your reference, we are updating the docs to include the SecureSuite membership information. Thank you for pointing out the omission and helping us improve our documentation.
